### ISSUE TITLE
NameError: global name 'loss' is not defined

### ISSUE THREAD

**Issue by SunHeng-BUPT** [marvis/pytorch-yolo3#17]
2018-05-07 11:31:59 epoch 0, processed 0 samples, lr 0.001000
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train(epoch)
  File "train.py", line 165, in train
    output = model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 66, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mcii/sunheng/pytorch-yolo3-master/darknet.py", line 153, in forward
    return loss
NameError: global name 'loss' is not defined

Hi, Firstly thanks to @marvis 's great work! I successfully trained my own data on pytorch-yolo2. But I got this error when I tried to train my own data on pytorch-yolo3. How can I fix this ? Thank you!

**Comment by zhouyuedlut** [comment]
the same error

**Comment by SunHeng-BUPT** [comment]
#

**Comment by yin1991999** [comment]
@SunHeng-BUPT 
does the train part work well?

**Comment by maxiaoliang1989120** [comment]
the same error

**Comment by d-colwell** [comment]
try changing the offending line to `this.loss`
Another note, make sure the batch size is divisible by the number of GPUs
