### ISSUE TITLE
NameError: global name 'loss' is not defined

### ISSUE THREAD

**Issue by cherishhh** [marvis/pytorch-yolo3#19]
Traceback (most recent call last):
  File "train.py", line 74, in <module>
    model       = Darknet(cfgfile)
  File "train.py", line 165, in train
    output = model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 68, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 78, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
NameError: global name 'loss' is not defined

**Comment by yin1991999** [comment]
same issue, i think yolo layer should not pass, it should return predicted value...
and then regoin loss calculate the loss on label data....then optimizor step based on grad.....

**Comment by MatthewLQM** [comment]
same issue， is there anybody find a solution to this?
@yin1991999 @cherishhh @marvis
