### ISSUE TITLE
 How to fix this bug?   RuntimeError: argument 1 (padding) must be tuple of int but got tuple of (float, float)

### ISSUE THREAD

**Issue by 17764591637** [marvis/pytorch-yolo3#24]
Loading weights from yolov3.weights... Done!
Traceback (most recent call last):
  File "detect.py", line 113, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 31, in detect
    boxes = do_detect(m, sized, 0.5, 0.4, use_cuda)
  File "/home/rps/Desktop/yolo3.pytorch/utils.py", line 337, in do_detect
    list_boxes = model(img)
  File "/home/rps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rps/Desktop/yolo3.pytorch/darknet.py", line 110, in forward
    x = self.models[ind](x)
  File "/home/rps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/rps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rps/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/rps/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 89, in conv2d
    torch.backends.cudnn.deterministic, torch.backends.cudnn.enabled)
RuntimeError: argument 1 (padding) must be tuple of int but got tuple of (float, float)

**Comment by banannakn** [comment]
https://github.com/marvis/pytorch-yolo2/issues/129
