### ISSUE TITLE
NameError: global name 'loss' is not defined

### ISSUE THREAD

**Issue by olgapeled** [marvis/pytorch-yolo3#30]
Hello,

I am freaking out -:( I successfully trained yolo2, but can't train yolo3.
I get the error : "NameError: global name 'loss' is not defined".

Traceback (most recent call last):
  File "/home/o/workspace/pytorch-yolo3/train.py", line 264, in <module>
    train(epoch)
  File "/home/o/workspace/pytorch-yolo3/train.py", line 165, in train
    output = model(data)
  File "/home/o/virtualenvs/yolo3-python2/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/o/workspace/pytorch-yolo3/darknet.py", line 153, in forward
    return loss
NameError: global name 'loss' is not defined

I use the master branch.
https://github.com/marvis/pytorch-yolo3

I tried:
python2 train.py cfg/voc.data cfg/yolov3.cfg yolov3.weights
OR
python2 train.py cfg/voc.data cfg/yolov3.cfg darknet53.conv.74

Please HELP!!!

**Comment by shuangyueliao** [comment]
how to solve this problem? Thanks.
