### ISSUE TITLE
assert(prev_width == out_widths[layers[1]])

### ISSUE THREAD

**Issue by jsxyzb** [marvis/pytorch-yolo3#31]
There are some differences
84 conv    256  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 256
85 upsample           * 2    13 x  13 x 256   ->    27 x  27 x 256
86 route  85 61
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 11, in detect
    m.print_network()
  File "/home/bozhang/pytorch-yolo3/darknet.py", line 158, in print_network
    print_cfg(self.blocks)
  File "/home/bozhang/pytorch-yolo3/cfg.py", line 134, in print_cfg
    assert(prev_width == out_widths[layers[1]])
AssertionError

How to fix it?

**Comment by hktxt** [comment]
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 11, in detect
    m.print_network()
  File "E:\condaDev\pytorch-yolo3-master\darknet.py", line 158, in print_network
    print_cfg(self.blocks)
  File "E:\condaDev\pytorch-yolo3-master\cfg.py", line 134, in print_cfg
    assert(prev_width == out_widths[layers[1]])
AssertionError
==============================================================
same problem

**Comment by xueshar** [comment]
branch python3 is not helpful, the same problem

 Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 11, in detect
    m.print_network()
  File "C:\Users\user\pytorch-yolo3\darknet.py", line 158, in print_network
    print_cfg(self.blocks)
  File "C:\Users\user\pytorch-yolo3\cfg.py", line 134, in print_cfg
    assert(prev_width == out_widths[layers[1]])
AssertionError

**Comment by xueshar** [comment]
problem solved by changing the code following the differences. branch python3 is download wrong
